# Generated by Django 5.0 on 2023-12-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProduk', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=255)),
                ('alco', models.CharField(max_length=200)),
            ],
        ),
    ]
