# Generated by Django 5.0 on 2023-12-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='perML',
            field=models.IntegerField(null=True),
        ),
    ]
